Algoritmo "Exercicio - Deposito"

// Disciplina   : [Lógica de Programação]
// Professor   : Marcos Monteiro
// Autor(a)    : Gabriel Gomes
// Data atual  : 15/12/2022

Var

saldo: real
deposito: real
saldoatualizado: real

Inicio

   saldo <- 500
   escreva ("Digite o valor do depósito: ")
   leia (deposito)
   saldoatualizado <- saldo + deposito
   escreval("Saldo Inicial: ", saldo)
   escreval("Depósito: ", deposito)
   escreval("Saldo Atualizado: ", saldoatualizado)
   
Fimalgoritmo