Algoritmo "Exercício - Endereço"
// Disciplina   : [Lógica de Programação]
// Professor   : Marcos Monteiro
// Descrição   : Programa para solicitar endereço da pessoa.
// Autor(a)    : Gabriel Gomes
// Data atual  : 15/12/2022
Var
// Seção de Declarações das variáveis
endereco: caractere


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva ("Digite seu endereço:")
   leia (endereco)
   escreva ("Seu endereço é: " + endereco)

Fimalgoritmo