Algoritmo "Exercicio - Tabuada-While"

// Disciplina   : [Lógica de Programação]
// Professor   : Marcos Monteiro
// Autor(a)    : Gabriel Gomes
// Data atual  : 15/12/2022

Var

numero, j, tabuada: inteiro

Inicio

    escreval("Digite um número:")
    leia(numero)
    escreval("Essa é a tabuada do número escolhido:")
    enquanto j <= 10 faca
         tabuada <- numero * j
         escreval(numero, " * ", j, " = ", tabuada)
         j <- j + 1
    fimenquanto
   
Fimalgoritmo